### ISSUE TITLE
Fix meta tags, add favicon

### ISSUE THREAD

**Issue by mckelveygreg** [EugTech/OpenEugeneFestivalWeb#30]
- [x] What are some meta tags, descriptions, etc we can add for SEO yadda yadda?
- [ ] Set image for when website is shared on social media
- [x] We need to logo to make a little favicon
